---
title: "hw4practice"
author: "chia-i,chou"
date: "July 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r cache=TRUE, warning=FALSE}
library(dplyr)
library(LaF)
```
## Regression(深度EDA)
## 資料為2011~2017職業傷害件數對行業部門
### From http://www.divxy123.ca/ReportBuilder2017/Pages/report_builder.php
```{r}
od1 = read.csv('./data/occupational disease1.csv')
``` 

### 資料結構
```{r}
od1 = od1 %>% filter( Gender == "Male" | Gender == "Female"  )
od1 = od1 %>% filter( Age.Group!='Not Available' )
od1$Injury.Illness.Year<- as.factor(od1$Injury.Illness.Year)
str(od1)  # check
```
```{r}
od1$total= od1$Agriculture   + od1$Automotive + od1$Chemicals.Process + od1$Construction + od1$Education + od1$Electrical + od1$Food  + od1$Forestry + od1$Health.Care + od1$Manufacturing + od1$ Mining  + od1$ Municipal + od1$Primary.Metals + od1$Pulp...Paper + od1$ Schedule.2  + od1$Services + od1$Transportation + od1$Unknown
head(od1)
```

### 基本統計
```{r}
summary(od1)
```

```{r cache=TRUE, warning=FALSE}
library(ggplot2)
#將底下的圖設定為黑白配色（theme_bw）
old <- theme_set(theme_bw())
```
### 性別v.s. 件數
1.畫圖,coord_flip() 函數使xy軸資料對調
2.結論:從圖中得出,男性的職業傷害件數七年來各年齡層的中位數高於女性
```{r cache=TRUE, warning=FALSE}
library(ggplot2)

ggplot(data = od1, aes(x = Gender , y = total )) +
 geom_boxplot() + coord_flip() +   
 labs( y = 'total', x = 'gender', 
       title = 'occupational_disease: gender v.s. total')
``` 

### 在95%信賴區間中,不同性別的件數之範圍如下
```{r cache=TRUE, warning=FALSE}
#以下函式計算95%信賴區間
with(od1,
     tapply(total, Gender,
     function(x) 
       c(mean(x) + c(-2, 2) * sd(x)/sqrt(length(x)))))
```
### 以下用 t-test 檢驗不同性別是否存在件數差異
```{r cache=TRUE, warning=FALSE}
#此函數會預設進行 Welch 校正，以處理兩樣本變異數不相同的問題
t.test( total~ Gender, data = od1)

#可加上參數 var.equal=TRUE 來假設變異數同值(不做Welch校正)
t.test(total~ Gender, data = od1, var.equal = TRUE)
```
## Part B. 年齡層  vs 件數
```{r cache=TRUE, warning=FALSE}
library(Hmisc)
```

```{r}
#看不同年齡下的職業傷害件數平均數
tapply(od1$total, od1$Age.Group, mean)
```

```{r}
ggplot(data = od1,  
       aes(x = Age.Group, y = total )) +
  stat_summary(fun.data = 'mean_cl_boot', size = 0.5) +
  scale_y_continuous(breaks = seq(600,3900, by = 300)) +
  geom_hline(yintercept = mean(od1$total) , 
             linetype = 'dotted') +
  labs(x = 'Age.Group ', y = 'total') +
  coord_flip()

```

### p<2.2e-16, 年齡與職業傷害件數平均數有顯著差異
```{r}
anova(m1 <- lm(total ~ Age.Group, data = od1))
```

```{r}
ggplot(data = od1, 
       aes(group = Age.Group, 
          y = total, x = Gender)) +
  geom_point() +
  stat_smooth(method = 'lm', se = F) +
  stat_smooth(aes(group = Age.Group, 
          y = total, x = Gender), 
          method = 'lm', se = F) + 
  facet_grid( . ~  Age.Group) +
  labs(x = '職業類別', y = '件數')
```
### 利用以下 ANOVA 檢驗假設是否正確
```{r}
#把性別加進模型
anova(m2 <- update(m1, . ~ . + 
            Gender, data = od1))
```
```{r}
#或許不是年齡層而是性別造成
anova(m3 <- update(m2, . ~ . - Age.Group,  data = od1))
```
```{r}
#將結果放在一個list中
res_lm <- lapply(list(m1, m2, m3), summary)
#比較在控制性別下，年齡層的效果
(res_lm[[2]]$r.sq - res_lm[[3]]$r.sq)/res_lm[[2]]$r.sq
```

```{r}
#比較在控年齡層下，性別的效果
(res_lm[[2]]$r.sq - res_lm[[1]]$r.sq)/res_lm[[1]]$r.sq
```

```{r}
anova(m1, m2)
```

```{r}
library(coefplot)
m2 <- lm(total ~ Age.Group+Gender- 1, 
         data = od1)
coefplot(m2, xlab = '估計值', ylab = '迴歸變項', title = '反應變項 = 職業傷害件數')
```
### 把資料與迴歸分析的預測值、殘差與影響度放進資料
```{r}
fit_m2 <- data.frame(od1[, c(2, 3, 22)], fitted = fitted(m2), resid = resid(m2),
                     infl = influence(m2)$hat )
```

###依年齡層疊合真實觀測值與預測值
```{r}
ggplot(data = fit_m2, aes(x =total, group = Age.Group )) +
 stat_density(geom = 'path', position = 'identity') +
 stat_density(geom = 'path', position = 'identity', aes(x = fitted)) +
 geom_vline(xintercept = c(with(od1, tapply(total,Age.Group, mean))), linetype = 'dotted')+
 facet_grid(Age.Group ~ .) +
 scale_x_continuous(breaks = seq(200, 900, by = 100))+
 labs(x = '職業傷害件數', y = '機率密度')
```

```{r}
ggplot(data = fit_m2, aes(x = scale(resid)), group = Age.Group ) +
 stat_density(geom = 'path', position = 'identity', aes(linetype = Age.Group)) +
 scale_linetype_manual(values = 11:1) +
 guides(linetype = guide_legend(reverse = TRUE)) +
 labs(x = '標準化殘差', y = '機率密度') +
 theme(legend.position = c(.15, .8))
```

```{r}
library(lattice)
qqmath(~ scale(resid) | Age.Group, data = fit_m2, type = c('p', 'g', 'r'),
       xlab = '常態位數', ylab = '標準化殘差', layout = c(2, 3),
       pch = '.', cex = 2)
```

```{r cache=TRUE, warning=FALSE}
library(MASS)
```

```{r}
ggplot(data = fit_m2, aes(x = fitted, y = scale(resid), group = Age.Group )) +
  geom_point(pch = 20, size = 1) +
  stat_smooth(method = 'rlm', se = F) +
  facet_grid(Age.Group ~ .) +
  labs(x = '件數預測值', y = '標準化殘差')
```

```{r}
ggplot(data = fit_m2, aes(x = infl, y = scale(resid), group = Age.Group)) +
 geom_text(aes(label = rownames(fit_m2)), cex = 2) +
 geom_hline(yintercept = 0, linetype = 'dotted') +
 facet_grid(Age.Group ~ .) +
 labs(x = '影響值', y = '標準化殘差')
```

```{r}
summary(influence(m2)$hat)
```

```{r}
theme_set(old)
```

```{r}
od1_inf <- od1[, c('total','Construction', 'Health.Care', 'Agriculture')]
```

```{r}
colMeans(od1_inf)
```

```{r cache=TRUE, warning=FALSE}
library(heplots)
scatterplotMatrix(~ total + Construction + Health.Care + Agriculture, data= od1_inf,
  pch = '.', cex = 3, smooth = FALSE, reg.line = FALSE, ellipse = TRUE,
  diagonal = 'none', lower.panel = NULL)
```

```{r}
library(corrplot)
corrplot(cor(od1_inf), method = 'ellipse', order = 'hclust', addrect = 4,
         type = 'upper', tl.pos = 'tp')
corrplot(cor(od1_inf), add = TRUE, type = 'lower', method = 'number',
         order = 'hclust', col = 'black', diag = FALSE, tl.pos = 'n', cl.pos = 'n')
```

```{r}
summary(m4 <- lm(total ~  Construction + Health.Care + Agriculture, data = od1_inf))
```

```{r}
coefplot(m4, predictors = c('Construction', 'Health.Care', 
                            'Agriculture'),
 xlab = '估計值', ylab = '迴歸變項(去除截距)', title = '反應變項是件數')
```

```{r}
library(effects)
plot(allEffects(m4), main = '', ylim = c(550, 670), grid = T)
```

```{r}
library(lm.beta)
summary(lm.beta(m4))
```

```{r}
summary(m5 <- update(m4, . ~ . - Agriculture , data = od1_inf))
```

```{r}
anova(m5, m4)
```