---
title: "EDA"
author: "chia-i,chou"
date: "July 18, 2018"
output: html_document
---
# 心得

##data From https://www.kaggle.com/mrisdal/exploring-survival-on-the-titanic/data


## 載入安裝包
```{r}
library('ggplot2') # visualization
library('ggthemes') # visualization
library('scales') # visualization
library('dplyr') # data manipulation
library('mice') # imputation
library('randomForest') # classification algorithm
```

## 匯入資料
```{r}
titanictest = read.csv('./DATA/ALL/test.csv')
titanictrain = read.csv('./DATA/ALL/train.csv')
full <- bind_rows(titanictrain, titanictest) # 將兩組乘客資(data.frame)料合併成一個檔,bind_rows在'dylpr'

str(full)  # check
```

## gsub分類出稱謂
```{r}
# Grab title from passenger names
full$Title <- gsub('(.*, )|(\\..*)', '', full$Name)

# Show title counts by sex
table(full$Sex, full$Title)
```

## 歸類出稀有姓氏 
```{r}
# Titles with very low cell counts to be combined to "rare" level
rare_title <- c('Dona', 'Lady', 'the Countess','Capt', 'Col', 'Don', 
                'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer')

# Also reassign mlle, ms, and mme accordingly
full$Title[full$Title == 'Mlle']        <- 'Miss' 
full$Title[full$Title == 'Ms']          <- 'Miss'
full$Title[full$Title == 'Mme']         <- 'Mrs' 
full$Title[full$Title %in% rare_title]  <- 'Rare Title'

# Show title counts by sex again
table(full$Sex, full$Title)
```

## 運用sapply和strsplit分割出姓氏 
```{r}
# Finally, grab surname from passenger name
full$Surname <- sapply(full$Name,  
                      function(x) strsplit(x, split = '[,.]')[[1]][1])
```

##  歸類出乘客家人總數加上姓氏
```{r}
# Create a family size variable including the passenger themselves
full$Fsize <- full$SibSp + full$Parch + 1 # 1代表乘客本身

# Create a family variable 
full$Family <- paste(full$Surname, full$Fsize, sep='_')
```

## 家庭人數與是否生還
```{r}
ggplot(full[1:891,], aes(x = Fsize, fill = factor(Survived))) +  # 編號891後的資料Survived為NA
  geom_bar(stat='count', position='dodge') +
  scale_x_continuous(breaks=c(1:11)) +  # max(full$Fsize)為11
  labs(x = 'Family Size') + 
  theme_few() # 去掉背景的網格,變白背黑框
```





## 家庭人數與是否生還畫出馬賽克圖
 - 方塊分類寬度=此類方塊的資料量(單身的最寬資料數最多),標準化殘差(standardized residual)

## 結論:4人以下小家庭生存'率'(比例)最高(深藍)
```{r}
# Discretize family size
full$FsizeD[full$Fsize == 1] <- 'singleton'
full$FsizeD[full$Fsize < 5 & full$Fsize > 1] <- 'small'
full$FsizeD[full$Fsize > 4] <- 'large'

# Show family size by survival using a mosaic plot
mosaicplot(table(full$FsizeD, full$Survived), main='Family Size by Survival', shade=TRUE) 
```


## 分類出小孩和媽媽
```{r}
# Create the column child, and indicate whether child or adult
full$Child[full$Age < 18] <- 'Child'
full$Child[full$Age >= 18] <- 'Adult'

# Show counts
table(full$Child, full$Survived)
```

## 分類出媽媽與非媽媽,(為女性+有小孩+大於18歲+稱謂不為miss)
```{r}
# Adding Mother variable
full$Mother <- 'Not Mother'  # 將此列加入
full$Mother[full$Sex == 'female' & full$Parch > 0 & full$Age > 18 & full$Title != 'Miss'] <-'Mother'  # Parch為小孩的數量

# Show counts
table(full$Mother, full$Survived)

```



