---
title: "Untitled"
author: "chia-i,chou"
date: "2018年7月24日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(bitops)
library(httr)
library(RCurl)
library(XML)
library(tm)
```

```{r}
library(NLP)
library(tmcn)
```

```{r}
library(jiebaRD)
library(jiebaR)
```

```{r}
from <- 1370 # 2018-03-25
to   <- 1384 # 2018-03-31
prefix = "https://www.ptt.cc/bbs/WorldCup/index"

data <- list()
for( id in c(from:to) )
{
  url  <- paste0( prefix, as.character(id), ".html" )
  html <- htmlParse( GET(url) )
  url.list <- xpathSApply( html, "//div[@class='title']/a[@href]", xmlAttrs )
  data <- rbind( data, as.matrix(paste('https://www.ptt.cc', url.list, sep='')) )
}
data <- unlist(data)

head(data)
```

```{r}
library(dplyr)
getdoc <- function(url)
{
    html <- htmlParse( getURL(url) )
    doc  <- xpathSApply( html, "//div[@id='main-content']", xmlValue )
    time <- xpathSApply( html, "//*[@id='main-content']/div[4]/span[2]", xmlValue )
    temp <- gsub( "  ", " 0", unlist(time) )
    part <- strsplit( temp, split=" ", fixed=T )
    #date <- paste(part[[1]][2], part[[1]][3], part[[1]][5], sep="-")
    #date <- paste(part[[1]][2], part[[1]][5], sep="_")
    #date <- paste(part[[1]][1], part[[1]][2], sep="_")
    timestamp <- part[[1]][4]
    timestamp <- strsplit( timestamp, split=":", fixed=T )
    hour <- timestamp[[1]][1]
    #print(hour)
    name <- paste0('./try2/', hour, ".txt")
    write(doc, name, append = TRUE)
}

sapply(data, getdoc)
```